### ISSUE TITLE
Powerup / Rapid Fire

### ISSUE THREAD

**Issue by LewFort** [ksu-cs-robotics/fall-2019-gdp-main-project-arcadedream#57]
Timeline: Sep 16 - 17

**Comment by jdotson97** [comment]
Remember, all you need to do to for this one is change 'primaryWeapon_m' in PlayerShip from PlayerWeapons.Standard to PlayerWeapons.IncreasedFireRate for the duration of the power-up. Should make it pretty easy to implement.
